# Generated by Django 3.0.7 on 2020-07-03 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dhtsensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_request', models.BooleanField(default=False)),
                ('water_time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 3, 11, 53, 23, 249795))),
            ],
        ),
    ]
