# Generated by Django 3.0.7 on 2020-07-03 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_watering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_request', models.BooleanField(default=False)),
                ('fan_time', models.DateTimeField(default=datetime.datetime(2020, 7, 3, 11, 55, 35, 812982))),
            ],
        ),
        migrations.AlterField(
            model_name='watering',
            name='water_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 3, 11, 55, 35, 812628)),
        ),
    ]
