# Generated by Django 3.0.7 on 2020-07-21 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200703_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watering',
            name='water_time',
        ),
        migrations.AlterField(
            model_name='fan',
            name='fan_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 9, 47, 6, 425798)),
        ),
    ]
