# Generated by Django 3.0.7 on 2020-07-21 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200721_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='watering',
            name='water_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 21, 9, 54, 4, 454606)),
        ),
        migrations.AlterField(
            model_name='fan',
            name='fan_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 9, 54, 4, 454954)),
        ),
    ]
