# Generated by Django 3.0.7 on 2020-07-21 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200721_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='fan_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 11, 4, 19, 912293)),
        ),
        migrations.AlterField(
            model_name='watering',
            name='water_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
