# Generated by Django 3.0.7 on 2020-07-21 06:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200721_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='fan_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 11, 10, 55, 534826)),
        ),
        migrations.AlterField(
            model_name='watering',
            name='water_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 6, 40, 55, 518158, tzinfo=utc)),
        ),
    ]
