# Generated by Django 3.0.7 on 2020-07-21 06:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200721_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='fan_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 11, 19, 6, 854140)),
        ),
        migrations.AlterField(
            model_name='watering',
            name='water_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 6, 49, 6, 837484, tzinfo=utc)),
        ),
    ]
