# Generated by Django 3.0.7 on 2020-07-21 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200721_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='fan_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 11, 20, 18, 925771)),
        ),
        migrations.AlterField(
            model_name='watering',
            name='water_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 21, 11, 20, 18, 925409)),
        ),
    ]
