# Generated by Django 3.0.7 on 2020-07-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200721_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fan',
            name='fan_time',
        ),
        migrations.RemoveField(
            model_name='watering',
            name='water_time',
        ),
    ]
