# Generated by Django 3.0.7 on 2020-07-22 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_watering_water_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='fan_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 11, 25, 35, 990529)),
        ),
        migrations.AlterField(
            model_name='watering',
            name='water_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 11, 25, 35, 990174)),
        ),
    ]
