# Generated by Django 3.0.7 on 2020-07-22 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200722_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='fan_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 7, 22, 12, 11, 34, 769388)),
        ),
        migrations.AlterField(
            model_name='watering',
            name='water_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 7, 22, 12, 11, 34, 769040)),
        ),
    ]
