# Generated by Django 3.0.7 on 2020-07-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200722_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fan',
            name='fan_time',
        ),
        migrations.RemoveField(
            model_name='watering',
            name='water_time',
        ),
    ]
