# Generated by Django 3.0.7 on 2020-07-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200722_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fan',
            name='fan_request',
        ),
        migrations.RemoveField(
            model_name='watering',
            name='water_request',
        ),
    ]
